"use client";

import { useRouter } from "next/navigation";
import { X } from "lucide-react";

export default function TermsPage() {
  const router = useRouter();

  return (
    <main className="relative min-h-screen bg-premium text-white isolate">
      {/* Subtle ambient glow */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-48 bg-[radial-gradient(ellipse_at_top,rgba(251,191,36,0.12),transparent_65%)]" />

      {/* Close button */}
      <button
        onClick={() => router.back()}
        aria-label="Close Terms of Service"
        className="
          fixed right-5 top-5 z-20
          inline-flex h-10 w-10 items-center justify-center
          rounded-full border border-white/15
          bg-white/5 backdrop-blur-md
          text-white/70 shadow-lg
          transition-all duration-200
          hover:bg-white/10 hover:text-white hover:border-white/30
          focus:outline-none focus:ring-2 focus:ring-amber-400/30
        "
      >
        <X className="h-4 w-4" />
      </button>

      {/* Content */}
      <div className="relative mx-auto max-w-3xl px-6 py-16 md:py-20">
        {/* Header */}
        <header className="mb-10 text-center">
          <h1 className="text-3xl md:text-4xl font-semibold tracking-tight">
            Terms of Service
          </h1>

          <p className="mt-2 text-sm text-white/55">
            Effective date: January 2026
          </p>

          <div className="mx-auto mt-6 h-px w-24 bg-white/10" />
        </header>

        {/* Body */}
        <section className="space-y-6 text-sm leading-relaxed text-white/80">
          <p>
            <strong className="font-medium text-white/90">PriceIQ Ltd</strong>{" "}
            (“PriceIQ”, “we”, “us”) provides a pricing and fee
            decision-support tool designed to help businesses model outcomes,
            compare scenarios, and understand the impact of fees and pricing
            structures. By accessing or using PriceIQ, you agree to these Terms
            of Service.
          </p>

          <p>
            PriceIQ is provided for informational and analytical purposes only.
            It does <strong>not</strong> constitute financial, legal,
            accounting, or tax advice. You remain solely responsible for any
            decisions made based on information generated by the service.
          </p>

          <p>
            While we make reasonable efforts to ensure calculations and outputs
            are accurate, PriceIQ relies on user-supplied data, assumptions,
            and third-party fee structures. We do not warrant that results are
            error-free, complete, or suitable for any particular purpose.
          </p>

          <p>
            To the maximum extent permitted by law, PriceIQ Ltd shall not be
            liable for any direct, indirect, incidental, consequential, or
            business losses arising from use of, or reliance on, the service.
          </p>

          <p>
            We may update, modify, suspend, or discontinue any part of the
            service at any time without notice, including features, pricing
            models, or availability.
          </p>

          <p>
            These Terms are governed by and construed in accordance with the laws of Scotland, and any disputes shall be subject to the exclusive jurisdiction of the Scottish courts.
          </p>
        </section>

        {/* Footer hint */}
        <footer className="mt-12 text-center text-[11px] text-white/45">
          © {new Date().getFullYear()} PriceIQ Ltd. All rights reserved.
        </footer>
      </div>
    </main>
  );
}
